version: '3'

services:
  db:
    image: postgres:alpine3.18
    container_name: portafolio_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dbadmin
      POSTGRES_USER: dbadmin
      POSTGRES_DB: portafolio_db

volumes:
  dbdata: